version: "3"
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: gse
    ports:
      - "3306:3306"

  backend:
    build:
      context: ./GSE_Backend/GSE
    ports:
      - "8085:8085"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/gse
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD:
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=  --execute 'SHOW DATABASES;'"
      interval: 5s
      timeout: 2s
      retries: 100

  frontend:
    build:
      context: ./GSE_Frontend/gse
    ports:
      - "80:80"
    depends_on:
      - backend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:80"